# Generated by Django 5.2.6 on 2025-09-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_copy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterModelTable(
            name='product',
            table='shop_copy_product',
        ),
    ]
